version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: Hemanthhj1
    ports: ["55432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  api:
    image: crm-api:local
    depends_on: [db]
    environment:
      NODE_ENV: production
      PORT: "4000"
      DATABASE_URL: "postgresql://crm_user:Hemanthhj1@db:5432/crm_db"
      JWT_SECRET: "dev-secret"
      SMTP_HOST: "smtp.example.com"
      SMTP_PORT: "587"
      SMTP_USER: "noreply@example.com"
      SMTP_PASS: "pass"
    ports: ["4000:4000"]
    volumes: ["crm-uploads:/app/uploads"]

  web:
    image: crm-web:local
    depends_on: [api]
    ports: ["8080:80"]

volumes:
  pgdata:
  crm-uploads: